version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SERVICE_FQDN_NEWAPI_3000
      - SQL_DSN=root:Kj9#mP2$vL5@tcp(mysql:3306)/new-api
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - SESSION_SECRET=xK8#pL9$mN4@vR2*qY7
      - NODE_TYPE=master
      - SYNC_FREQUENCY=300
      - FRONTEND_BASE_URL=${SERVICE_FQDN_NEWAPI_3000}

    depends_on:
      - redis
      - mysql
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kj9#mP2$vL5
      MYSQL_DATABASE: new-api
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"  # 如果需要从外部访问MySQL，取消注释此行

volumes:
  mysql_data:
